In [34]:
import pandas as pd

df_aluno = pd.read_json('thiago/Aluno.json')
df_BeneficioGovernoFederal = pd.read_json("thiago/BeneficioGovernoFederal.json")
df_Caracterizacao = pd.read_json("thiago/Caracterizacao.json")
df_CompanhiaDomiciliar = pd.read_json("thiago/CompanhiaDomiciliar.json")
df_ContribuinteRendaFamiliar = pd.read_json("thiago/ContribuinteRendaFamiliar.json")
df_CursoCampus = pd.read_json("thiago/CursoCampus.json")
df_EstadoCivil = pd.read_json("thiago/EstadoCivil.json")
df_Idioma = pd.read_json("thiago/Idioma.json")
df_MatriculaPeriodo = pd.read_json("thiago/MatriculaPeriodo.json")
df_MeioTransporte = pd.read_json("thiago/MeioTransporte.json")
df_NecessidadeEspecial = pd.read_json("thiago/NecessidadeEspecial.json")
df_Raca = pd.read_json("thiago/Raca.json")
df_RazaoAfastamentoEducacional = pd.read_json("thiago/RazaoAfastamentoEducacional.json")
df_SituacaoMatricula = pd.read_json("thiago/SituacaoMatricula.json")
df_SituacaoMatriculaPeriodo = pd.read_json("thiago/SituacaoMatriculaPeriodo.json")
df_SituacaoTrabalho = pd.read_json("thiago/SituacaoTrabalho.json")
df_TipoAcessoInternet = pd.read_json("thiago/TipoAcessoInternet.json")
df_TipoAreaResidencial = pd.read_json("thiago/TipoAreaResidencial.json")
df_TipoEscola = pd.read_json("thiago/TipoEscola.json")
df_TipoImovelResidencial = pd.read_json("thiago/TipoImovelResidencial.json")
df_TipoServicoSaude = pd.read_json("thiago/TipoServicoSaude.json")

In [53]:

print("Aluno:", df_aluno.shape, "\n", df_aluno[0:2], "\n --- \n")
print("BeneficioGovernoFederal:", df_BeneficioGovernoFederal.shape, "\n",df_BeneficioGovernoFederal, "\n --- \n")
print("CompanhiaDomiciliar:", df_CompanhiaDomiciliar.shape, "\n",df_CompanhiaDomiciliar, "\n --- \n")
print("ContribuinteRendaFamiliar:", df_ContribuinteRendaFamiliar.shape,"\n", df_ContribuinteRendaFamiliar, "\n --- \n")
print("CursoCampus:", df_CursoCampus.shape, "\n",df_CursoCampus, "\n --- \n")
print("EstadoCivil:", df_EstadoCivil.shape, "\n",df_EstadoCivil, "\n --- \n")
print("Idioma:", df_Idioma.shape, "\n",df_Idioma, "\n --- \n")
print("MatriculaPeriodo:", df_MatriculaPeriodo.shape, "\n",df_MatriculaPeriodo[0:2], "\n --- \n")
print("MeioTransporte:", df_MeioTransporte.shape, "\n",df_MeioTransporte, "\n --- \n")
print("NecessidadeEspecial:", df_NecessidadeEspecial.shape, "\n",df_NecessidadeEspecial, "\n --- \n")
print("Raca:", df_Raca.shape, "\n",df_Raca, "\n --- \n")
print("RazaoAfastamentoEducacional:", df_RazaoAfastamentoEducacional.shape, "\n",df_RazaoAfastamentoEducacional, "\n --- \n")
print("SituacaoMatricula:", df_SituacaoMatricula.shape,"\n",df_SituacaoMatricula, "\n --- \n")
print("SituacaoMatriculaPeriodo:", df_SituacaoMatriculaPeriodo.shape, "\n",df_SituacaoMatriculaPeriodo, "\n --- \n")
print("SituacaoTrabalho:", df_SituacaoTrabalho.shape,"\n", df_SituacaoTrabalho, "\n --- \n")
print("TipoAcessoInternet:", df_TipoAcessoInternet.shape, "\n",df_TipoAcessoInternet, "\n --- \n")
print("TipoAreaResidencial:", df_TipoAreaResidencial.shape, "\n",df_TipoAreaResidencial, "\n --- \n")
print("TipoEscola:", df_TipoEscola.shape, "\n",df_TipoEscola, "\n --- \n")
print("TipoImovelResidencial:", df_TipoImovelResidencial.shape, "\n",df_TipoImovelResidencial, "\n --- \n")
print("TipoServicoSaude:", df_TipoServicoSaude.shape,"\n", df_TipoServicoSaude, "\n --- \n")

print("Caracterizacao:", df_Caracterizacao.shape, df_Caracterizacao[0:2])

Aluno: (5257, 5)
    ano_letivo__ano  curso_campus_id            id  periodo_letivo  situacao_id
0             2013              441  6.881203e+30               2            9
1             2008               83  2.089774e+29               2            9
 ---

BeneficioGovernoFederal: (3, 2)
                                           descricao  id
0  Programa Benefício de Prestação Continuada - BPC   5
1                            Programa Bolsa Família   3
2      Programa de Erradicação do Trabalho Infantil   4
 ---

CompanhiaDomiciliar: (8, 2)
                 descricao  id
0                     Pai  13
1                     Mãe  14
2                    Pais   7
3              Sozinho(a)  11
4                 Cônjuge  10
5                  Outros  12
6  Parente(s) ou amigo(s)   8
7           Não informado   9
 ---

ContribuinteRendaFamiliar: (10, 2)
          descricao  id
0              Pai  10
1              Mãe  11
2          Cônjuge  13
3           Avô(ó)  14
4           Tio(a)  15
5         Irmão(ã)  16
6         Parentes  17
7           Outros  18
8  O próprio aluno  12
9    Não informado  19
 ---

CursoCampus: (5, 2)
                                            descricao   id
0  Técnico de Nível Médio em Segurança do Trabalh...  420
1  Licenciatura em Espanhol [2006-2011] - Campus ...   83
2  Licenciatura em Espanhol [2012] - Campus Natal...  499
3   Licenciatura em Letras Espanhol EaD - Campus EaD  441
4  Técnico de Nível Médio em Segurança do Trabalh...  411
 ---

EstadoCivil: (6, 2)
        descricao  id
0    Solteiro(a)   6
1      Casado(a)   7
2  União Estável   8
3  Divorciado(a)   9
4       Viúvo(a)  10
5  Não declarado  11
 ---

Idioma: (5, 3)
   descricao  id uso_caracterizacao
0    Inglês   5               True
1  Espanhol   6               True
2   Francês   7               True
3     Outro   8               True
4   Japonês   9              False
 ---

MatriculaPeriodo: (19756, 4)
        aluno_id  ano_letivo__ano  periodo_letivo  situacao_id
0  7.619035e+31             2004               2           18
1  8.970519e+29             2008               2           11
 ---

MeioTransporte: (9, 2)
                           descricao  id
0                 Transporte locado  17
1                         Bicicleta   9
2                              Moto  10
3                         Automóvel  12
4               Transporte coletivo  13
5  Transporte cedido por prefeitura  14
6                              A pé  15
7                             Outro  16
8                          Mototáxi  11
 ---

NecessidadeEspecial: (7, 2)
                        descricao  id
0                       Auditiva   8
1                         Física   9
2                         Mental  10
3                         Visual  12
4               Condutas Típicas  13
5  Superdotado/Altas habilidades  14
6                       Múltipla  11
 ---

Raca: (6, 5)
    codigo_censup  codigo_siape      descricao  id inativo_siape
0              3             4          Parda   1         False
1              2             6          Preta   2         False
2              1             1         Branca   3         False
3              5             5       Indígena   4         False
4              4             3        Amarela   5         False
5              0             9  Não declarado   7         False
 ---

RazaoAfastamentoEducacional: (5, 2)
                                            descricao  id
0                                 Falta de Motivação   8
1  Baixa condição financeira para se manter na es...   7
2                                        Outra razão  10
3  Necessidade de trabalhar para ajudar no susten...   6
4                             Nunca parou de estudar  11
 ---

SituacaoMatricula: (25, 2)
                           descricao   id
0                          Afastado    8
1        Aguardando Colação de Grau   13
2                  Aguardando ENADE   16
3              Aguardando Seminário   15
4                         Cancelado   10
5          Cancelamento Compulsório   20
6                  Certificado ENEM   14
7                       Concludente    5
8                         Concluído    6
9                           Egresso   18
10         Estagiario (Concludente)   12
11                           Evasão    9
12                         Falecido    7
13                          Formado   19
14                      Intercâmbio   17
15                         Jubilado    3
16                      Matriculado    1
17  Matrícula Vínculo Institucional   21
18                    Não Concluído  102
19                    Não concluído  100
20                         Trancado    2
21         Trancado Voluntariamente   99
22              Transferido Externo   11
23              Transferido Interno    4
24                 Transferido SUAP  101
 ---

SituacaoMatriculaPeriodo: (26, 2)
                           descricao   id
0                          Afastado    5
1                          Aprovado   11
2                  Aproveit. Módulo   20
3                         Cancelada    4
4          Cancelamento Compulsório   23
5                  Certificado ENEM   22
6                       Dependência   10
7                         Em Aberto    1
8           Estágio e/ou Monografia   17
9                            Evasão   15
10             Fechado c/ Pendência   19
11                      Intercâmbio   24
12                         Jubilado   14
13                      Matriculado    2
14  Matrícula Vínculo Institucional   21
15                  Período Fechado   18
16                       Rep. Falta   16
17                        Reprovado   12
18                         Trancada    3
19         Trancado Voluntariamente   99
20                    Transf. Curso    9
21                  Transf. Externa    6
22              Transf. Instituição    7
23                    Transf. Turno    8
24                 Transferido SUAP  100
25           Vindo de Transferência   13
 ---

SituacaoTrabalho: (12, 2)
                               descricao  id
0                              Autônomo   7
1                  Não está trabalhando   8
2                            Aposentado  10
3                       Serviço público  12
4     Trabalha com vínculo empregatício   6
5                       Nunca trabalhou   9
6                      Estágio ou bolsa  13
7          Trabalhador rural/Agricultor  14
8                              Pescador  15
9   Beneficiário ou Pensionista do INSS  16
10                        Não informado  18
11                      Empresa privada  17
 ---

TipoAcessoInternet: (6, 2)
           descricao  id
0       Diariamente   1
1  A cada dois dias   2
2      Semanalmente   3
3    Quinzenalmente   4
4       Mensalmente   5
5        Não acesso   6
 ---

TipoAreaResidencial: (5, 2)
                descricao  id
0                 Urbana   5
1                  Rural   6
2    Comunidade Indígena   7
3  Comunidade Quilombola   8
4          Não informado   9
 ---

TipoEscola: (9, 2)
                                            descricao  id
0                          Somente em escola pública   1
1                    A maior parte em escola pública   2
2                       Somente em escola particular   3
3                 A maior parte em escola particular   4
4                         Somente em escola indígena   5
5                   A maior parte em escola indígena   6
6                               Outro tipo de escola   9
7  Somente em escola situada em comunidade quilom...   7
8  A maior parte em escola situada em comunidade ...   8
 ---

TipoImovelResidencial: (7, 2)
                   descricao  id
0  Pensionato ou Alojamento  11
1                     Outro  12
2                   Próprio   6
3                Financiado   7
4                   Alugado   8
5      Cedido ou Emprestado   9
6             Não informado  10
 ---

TipoServicoSaude: (4, 2)
                        descricao  id
0      Plano de saúde particular   1
1      Plano de saúde da empresa   2
2   Sistema Único de Saúde - SUS   3
3  Consultas/Exames particulares   4
 ---

Caracterizacao: (3643, 38)   aluno_exclusivo_rede_publica      aluno_id  companhia_domiciliar_id  \
0                        False  9.441839e+31                       11
1                         True  9.522118e+31                        8

   ensino_fundamental_conclusao  ensino_medio_conclusao  \
0                             0                  1998.0
1                          2007                  2010.0

   escola_ensino_fundamental_id  escola_ensino_medio_id  estado_civil_id  \
0                           NaN                     1.0                6
1                           1.0                     1.0                6

   ficou_tempo_sem_estudar  frequencia_acesso_internet_id  \
0                      1.0                            1.0
1                      1.0                            NaN

          ...           renda_bruta_familiar  renda_per_capita  \
0         ...                            0.0              0.00
1         ...                         1800.0              0.46

  responsavel_financeir_trabalho_situacao_id  responsavel_financeiro_id  \
0                                          8                         12
1                                         17                         12

  responsavel_financeiro_nivel_escolaridade_id tempo_sem_estudar  \
0                                           20               3.0
1                                           16               NaN

   tipo_area_residencial_id tipo_imovel_residencial_id  tipo_servico_saude_id  \
0                         5                          8                    NaN
1                         5                          8                    NaN

  trabalho_situacao_id
0                    8
1                   17

[2 rows x 38 columns]

In [51]:
#id_aluno = df_aluno['id'][1]
#id_aluno_2 = df_Caracterizacao['aluno_id'][0]
#print(id_aluno)
#print(df_Caracterizacao['aluno_id'][ df_Caracterizacao['aluno_id'] == id_aluno ])
#print(df_Caracterizacao['aluno_id'][ df_Caracterizacao['aluno_id'] == id_aluno_2 ])

#l = [a for a in df_aluno['id'] if df_Caracterizacao['aluno_id'][ df_Caracterizacao['aluno_id'] == a ] ] 
#for a in df_aluno['id']:
#    print(df_Caracterizacao['aluno_id'][ df_Caracterizacao['aluno_id'] == a ])
    #break

In [65]:
print(df_Caracterizacao.shape)
print(df_Caracterizacao.keys())

#masking
df_Caracterizacao['renda_per_capita'][ (df_Caracterizacao['renda_per_capita'] > 1.0) & (df_Caracterizacao['renda_per_capita'] < 2.0)].shape

#fancy indexing
df_Caracterizacao[['renda_per_capita', 'renda_bruta_familiar']]

#transposta 
df_Caracterizacao.T

#misturar maskin e fancy
df_Caracterizacao.loc[df_Caracterizacao.renda_per_capita > 2, ['aluno_exclusivo_rede_publica', 'ensino_medio_conclusao']]

(3643, 38)
Index(['aluno_exclusivo_rede_publica', 'aluno_id', 'companhia_domiciliar_id',
       'ensino_fundamental_conclusao', 'ensino_medio_conclusao',
       'escola_ensino_fundamental_id', 'escola_ensino_medio_id',
       'estado_civil_id', 'ficou_tempo_sem_estudar',
       'frequencia_acesso_internet_id', 'historico_caracterizacao_id', 'id',
       'local_acesso_internet', 'mae_nivel_escolaridade_id',
       'nome_escola_ensino_fundamental', 'nome_escola_ensino_medio',
       'pai_nivel_escolaridade_id', 'possui_conhecimento_idiomas',
       'possui_conhecimento_informatica', 'possui_necessidade_especial',
       'qtd_filhos', 'qtd_pessoas_domicilio', 'quantidade_computadores',
       'quantidade_netbooks', 'quantidade_notebooks', 'quantidade_smartphones',
       'raca_id', 'razao_ausencia_educacional_id', 'renda_bruta_familiar',
       'renda_per_capita', 'responsavel_financeir_trabalho_situacao_id',
       'responsavel_financeiro_id',
       'responsavel_financeiro_nivel_escolaridade_id', 'tempo_sem_estudar',
       'tipo_area_residencial_id', 'tipo_imovel_residencial_id',
       'tipo_servico_saude_id', 'trabalho_situacao_id'],
      dtype='object')

     aluno_exclusivo_rede_publica  ensino_medio_conclusao
2                           False                  2003.0
3                            True                  2002.0
7                           False                     NaN
22                          False                     0.0
23                          False                  2005.0
32                          False                  2005.0
36                          False                  2008.0
45                           True                  2003.0
47                          False                  2010.0
55                          False                  1994.0
67                          False                  2006.0
75                          False                  2013.0
83                          False                  2003.0
111                         False                  2002.0
120                         False                  1996.0
123                         False                  1998.0
142                         False                  2005.0
151                          True                  2004.0
160                         False                  2011.0
181                         False                  2000.0
184                         False                  1993.0
189                          True                  1999.0
195                         False                     0.0
212                         False                  2011.0
225                          True                  2014.0
306                          True                     NaN
353                          True                  2003.0
355                         False                  2005.0
407                         False                  2002.0
417                          True                  2008.0
...                           ...                     ...
3146                        False                  2000.0
3148                        False                  2008.0
3174                        False                     0.0
3202                        False                  1989.0
3227                        False                  2001.0
3234                        False                  1994.0
3257                        False                  2011.0
3280                        False                  2006.0
3287                        False                  2004.0
3313                         True                  2008.0
3354                        False                  2008.0
3357                        False                     0.0
3380                        False                  2003.0
3389                        False                  2008.0
3404                        False                  2004.0
3411                        False                  1995.0
3429                        False                  2008.0
3432                        False                  1998.0
3442                        False                  2011.0
3462                         True                  2007.0
3481                         True                  2014.0
3502                        False                  2009.0
3521                        False                  1995.0
3522                        False                  2004.0
3528                        False                  2007.0
3559                        False                  1995.0
3586                        False                  2003.0
3598                        False                  1979.0
3619                        False                  2000.0
3622                        False                  2006.0

[228 rows x 2 columns]